# Generated by Django 3.2.9 on 2022-10-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_auto_20221028_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='Song',
            new_name='song_id',
        ),
    ]
